### ISSUE TITLE
Add hdf5_hl.lib

### ISSUE THREAD

**Issue by xiaoqiangwang** [areaDetector/ADBinaries#3]
For a NDArray processing plugin, I need to prototype a HDF5 writer to save both image and 1D spectrum extract from image. It seems hdf5_hl interface has made it much simpler. 

If hdf5_hl is anyway built, could it be included as a bonus?

**Comment by ulrikpedersen** [comment]
Are you planning to write a custom HDF5 file writer?

**Comment by xiaoqiangwang** [comment]
Kindof, to be able to save 1d data, such as spectra and photon events list, together with image.

I have the memory that the current writer is limited to scalar values.  Might it be changed in the meantime?

**Comment by MarkRivers** [comment]
You are correct that NDAttributes are currently limited to scalars.  One possible workaround is that attributes can be strings, with no length limitation.  So if you convert your 1-D array to a string you can save it as an attribute in the HDF5 file.

**Comment by xiaoqiangwang** [comment]
Mark: Yes, I am aware of this workaround, which you told me ~2 years ago. 

However the result file has to be read by different programs, MATLAB/Python/IGOR, it would be more intuitive and easy to write 1d vector directly.

**Comment by ulrikpedersen** [comment]
Support for 1D (or more D?) arrays in NDAttributes has been on the wish-list for a long time. Recently we have been putting some effort into adopting EPICS V4 NTNDArrays. I think this can be a starting point to allow more complex data structures (than scalars) to be attached to the image data.

For the whole of the collaboration it would be more beneficial in the long run if you would be willing to invest some development efforts into extending ADCore to support 1D arrays (possibly through the use of V4  NTNDArrays?) - rather building another custom HDF5 file writer plugin... :smiley: 


> If hdf5_hl is anyway built, could it be included as a bonus?

Sorry I didn't reply directly to this one at first. The answer is unfortunately no - I say unfortunately because I would also like to have the HL lib available. The trouble is that we build the HDF5 libs with the --threadsafe flag (because you can instantiate multiple HDF5 file writer plugins in separate threads) - and this build mode is incompatible with building the HL lib.

**Comment by xiaoqiangwang** [comment]
I see. Really a pity.

If I remember correctly, Mark has a concern about complex data as NDArray attribute. I forgot the exact reason.

**Comment by MarkRivers** [comment]
My concern is that it increases complexity
- What dimensions and data types of attributes do we support?
- Efficiently handling memory allocation, reference counting, etc.

If V4 has the tools to make this simple and fast we should consider it.

**Comment by ulrikpedersen** [comment]
I agree it will always a balance between complexity (advanced features) and performance... I hope that it can be done in a way so that if a user elects to not use complex structures, the performance remain high.

**Comment by ulrikpedersen** [comment]
With regards to the original question on this issue: 

> If hdf5_hl is anyway built, could it be included as a bonus?

I'm sorry to say the answer is no (see my previous comment for the reason) and so I am closing the issue. If the HDF Group eventually enables the combination of a threadsafe build with the HL library then I will definitely add it. In fact I have already brought up this issue with them.

I suggest creating another issue for the discussion of advanced/complex NDAttributes.
